quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.max-size=20
quarkus.flyway.clean-at-start=false
quarkus.flyway.migrate-at-start=true
quarkus.http.cors.enabled=true
quarkus.hibernate-orm.blocking=false
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.metrics.enabled=true
quarkus.hibernate-orm.query.fail-on-pagination-over-collection-fetch=true
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
# Frontend configuration
app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:3000}
