quarkus.datasource.devservices.port=5432
quarkus.datasource.devservices.reuse=true
quarkus.datasource.devservices.show-logs=true
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.flyway.locations=db/migration,db/dev
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.hibernate-orm.log.format-sql=false
quarkus.http.cors.origins=/.*/
app.frontend.base-url=http://localhost:3000