quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.reactive.url=postgresql://postgresql:5432/reservation_db
quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/reservation_db
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.log.format-sql=false
quarkus.hibernate-orm.sql-load-script=no-file
