quarkus.datasource.devservices.reuse=true
quarkus.datasource.devservices.show-logs=true
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.flyway.locations=db/migration
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.hibernate-orm.log.format-sql=false
quarkus.http.cors.origins=/.*/