ALTER TABLE seats ADD COLUMN email VARCHAR(255) NULL;
ALTER TABLE seats ADD COLUMN phone VARCHAR(50) NULL;
ALTER TABLE seats ADD COLUMN paid_at TIMESTAMP NULL;

CREATE INDEX idx_seats_email ON seats(email) WHERE email IS NOT NULL;
